As well as files or devices on the local filesystem, allow opening of file-like objects.
nathanhi/pyfatfs pull request #16
Opened 2022-01-25 20:24 UTC by dseeley

To avoid having to create temporary files on local media, allow manipulating file-like objects in-memory.

2022-01-26 08:57 UTC, nathanhi requested changes
Thank you for your pull request! Having the option to directly set a file pointer is a great idea!

In my opinion though, having a function serving multiple different purposes (opening a file or setting a file pointer) will lead to confusion ("why can I pass a file-like object as "filename?") and maintenance will become more difficult in the future (harder to unit test).

Is there any specific reason to have this in the `open` function instead of just offering a public `set_fp` function that I'm overlooking? If not, would you mind to expose this functionality in a new function instead?

2022-01-26 09:11 UTC, dseeley commented
> In my opinion though, having a function serving multiple different purposes (opening a file or setting a file pointer) will lead to confusion ("why can I pass a file-like object as `filename`?) and maintenance will become more difficult in the future (harder to unit test).
> 
> Is there any specific reason to have this in the `open` function instead of just offering a public `set_fp` function that I'm overlooking? If not, would you mind to expose this functionality in a new function instead?

Hi - perhaps this is merely ignorance of the interface on my part!

I'm trying to open a fat filesystem that is stored as a BytesIO object:
```python
    cidata_fatfs = PyFatFS(cidata__fat_bytestream)
    cidata_fatfs.writetext('/meta-data', META_DATA)
```

It seems the constructor requires a `filename`; is there another way to achieve what I'm attempting?

2022-02-01 09:26 UTC, dseeley commented
> It seems the constructor requires a `filename`; is there another way to achieve what I'm attempting?

Hi @nathanhi - have you had any more thoughts on this?  

I was trying to avoid modifying the signature of `PyFatFS` constructor - so it needs to take a `filename`.  This `filename` then has its `__fp` property set (after being opened, (or not, in the case of my PR)) in `PyFat.open`.  Is there a way to avoid any of this?

2022-02-02 20:22 UTC, nathanhi commented
Sorry for the delay! I went ahead and implemented my proposal:

https://github.com/nathanhi/pyfatfs/compare/feature/set_fp?expand=1

It can be used like this:

```python
in_memory_fs = BytesIO(b'your_raw_filesystem_data')
pf = PyFat()
pf.set_fp(in_memory_fs)
```

2022-02-02 22:06 UTC, dseeley commented
> Would this work for you? Implementing it like this would need the least compromise with regards to the API.

Hi - thanks for getting back!  I see this enables opening a BytesIO PyFat object, but does this enable me to open a PyFat**FS** with a BytesIO PyFat?  Is there a way to otherwise write to the PyFat object?

2022-02-03 16:55 UTC, nathanhi commented
> > Would this work for you? Implementing it like this would need the least compromise with regards to the API.
> 
> Hi - thanks for getting back! I see this enables opening a BytesIO PyFat object, but does this enable me to open a PyFat**FS** with a BytesIO PyFat? Is there a way to otherwise write to the PyFat object?

Yes, that's why I hid my answer - I overlooked that fact. I just released 1.0.0, which not only adds support for formatting a new filesystem, but also said set_fp  function as well as an ``pyfatfs.PyFatFS.PyFatBytesIOFS`` class, which should provide exactly what you need:

https://pyfatfs.readthedocs.io/en/stable/pyfatfs.PyFatFS.html#pyfatfs.PyFatFS.PyFatBytesIOFS

Looking forward to your feedback!

2022-02-03 17:15 UTC, dseeley commented
> Looking forward to your feedback!

Brilliant - works perfectly!  Thanks!

2022-02-03 17:15 UTC, closed without merging